<h1 align="center">Practical 2: Sorting and Filtering</h1>

### Import lib

In [1]:
import pandas as pd

### Read the dataset

In [6]:
df = pd.read_csv("chipotle.tsv", sep="\t")

In [17]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [19]:
df.shape

(4622, 5)

In [21]:
df.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [25]:
df["item_price"].head()

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
Name: item_price, dtype: str

In [26]:
df["item_price"] = df["item_price"].str.replace("$", "").astype("float64")

In [27]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [28]:
df.dtypes

order_id                int64
quantity                int64
item_name                 str
choice_description        str
item_price            float64
dtype: object

## Sorting and Filtering

### 11. How many products cost more than $10.00?

In [34]:
df.item_price > 10.00

0       False
1       False
2       False
3       False
4        True
        ...
4617     True
4618     True
4619     True
4620    False
4621    False
Name: item_price, Length: 4622, dtype: bool

In [38]:
df[df.item_price > 10.00]["order_id"].count()

np.int64(1130)

### 13. Sort the dataset by item

In [40]:
df.sort_values(by="item_name")

,order_id,quantity,item_name,choice_description,item_price
298,129,1,6 Pack Soft Drink,[Sprite],6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
357,154,1,6 Pack Soft Drink,[Coke],6.49
388,168,1,6 Pack Soft Drink,[Diet Coke],6.49
417,182,1,6 Pack Soft Drink,[Diet Coke],6.49
...,...,...,...,...,...
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98

### 14. What is the quantity of the most expensive item ordered?

In [52]:
df.sort_values(by="item_price", ascending=False)["quantity"].iloc[0]

np.int64(15)

In [78]:
df.loc[df["item_price"].idxmax()]["quantity"]

np.int64(15)

### 15. How many times was a veggie salad Bowl ordered?

In [55]:
df[df.item_name == "Veggie Salad Bowl"]["quantity"].sum()

np.int64(18)

### 16. How many times did someone order more than one canned soda?

In [59]:
condition = (df.quantity > 1) & (df.item_name == "Canned Soda")

In [65]:
df[condition]["order_id"].count()

np.int64(20)

### 17. How many different products are sold?

In [73]:
len(df.item_name.unique())

50

In [74]:
df.item_name.nunique()

50

In [72]:
df["item_name"].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4617     True
4618     True
4619     True
4620     True
4621     True
Name: item_name, Length: 4622, dtype: bool

### 18. What is the total revenue?

In [82]:
total_revenue = (df.item_price * df.quantity).sum()

In [83]:
total_revenue

np.float64(39237.02)

### 22. Which item has the highest average price?

In [89]:
df.groupby(by="item_name")["item_price"].mean().idxmax()

'Bowl'

### 23. How many items include chicken in their item name?

In [94]:
df[df.item_name.str.contains("Chicken")]["order_id"].count()

np.int64(1560)

## Questions

### 31. What was the most ordered items in the choice_description column?

In [159]:
def get_choice_list(value: str):
    return value.replace("[", "").replace("]", "").split(", ")

In [162]:
df.choice_description[df.choice_description.notna()].apply(get_choice_list).value_counts().index[0]

['Diet Coke']

 ### 32. What is the average revenue amount per order?

In [100]:
(df.quantity * df.item_price).mean()

np.float64(8.48918649935093)

### 33. Which product has the highest quantity sold?

In [124]:
df.sort_values("quantity", ascending=False)["item_name"].iloc[0]

'Chips and Fresh Tomato Salsa'

### 34. Calculate the average price of each product?

In [128]:
df.groupby(by="item_name")["item_price"].mean()

item_name
6 Pack Soft Drink                         6.610185
Barbacoa Bowl                            10.187273
Barbacoa Burrito                          9.832418
Barbacoa Crispy Tacos                    10.928182
Barbacoa Salad Bowl                      10.640000
Barbacoa Soft Tacos                      10.018400
Bottled Water                             1.867654
Bowl                                     14.800000
Burrito                                   7.400000
Canned Soda                               1.320577
Canned Soft Drink                         1.457641
Carnitas Bowl                            10.833971
Carnitas Burrito                         10.132712
Carnitas Crispy Tacos                    11.137143
Carnitas Salad                            8.990000
Carnitas Salad Bowl                      11.056667
Carnitas Soft Tacos                       9.398500
Chicken Bowl                             10.113953
Chicken Burrito                          10.082857
Chicken Crispy Tacos                     10.045319
Chicken Salad                             9.010000
Chicken Salad Bowl                       11.170455
Chicken Soft Tacos                        9.635565
Chips                                     2.342844
Chips and Fresh Tomato Salsa              3.285091
Chips and Guacamole                       4.595073
Chips and Mild Fresh Tomato Salsa         3.000000
Chips and Roasted Chili Corn Salsa        3.084091
Chips and Roasted Chili-Corn Salsa        2.390000
Chips and Tomatillo Green Chili Salsa     3.087209
Chips and Tomatillo Red Chili Salsa       3.072917
Chips and Tomatillo-Green Chili Salsa     2.544194
Chips and Tomatillo-Red Chili Salsa       2.987500
Crispy Tacos                              7.400000
Izze                                      3.390000
Nantucket Nectar                          3.641111
Salad                                     7.400000
Side of Chips                             1.840594
Steak Bowl                               10.711801
Steak Burrito                            10.465842
Steak Crispy Tacos                       10.209714
Steak Salad                               8.915000
Steak Salad Bowl                         11.847931
Steak Soft Tacos                          9.746364
Veggie Bowl                              10.211647
Veggie Burrito                            9.839684
Veggie Crispy Tacos                       8.490000
Veggie Salad                              8.490000
Veggie Salad Bowl                        10.138889
Veggie Soft Tacos                        10.565714
Name: item_price, dtype: float64

### 35. Which choice appears most often?

In [154]:
df.item_name.value_counts().index[0]

'Chicken Bowl'