<h1 align="center">📄Assignment 2 (Questions): (Knowing your data, filtering, and sorting)</h1>

## Supermarket Sales Data Analysis – Filtering, Sorting & Aggregation

#### Description & Objectives

This assignment evaluates your proficiency in Exploratory Data Analysis using Python Pandas. Working with the ```SuperMarket
Analysis.csv``` dataset (1,000 transactions across three branches), you will demonstrate competency in data ingestion, quality
assessment, conditional filtering, multi-criteria sorting, and group-based aggregation. The exercise requires you to extract
actionable business insightsincluding revenue patterns by branch/demographic, product performance metrics, and customer
behavior indicators—through programmatic data manipulation without modifying source data.

**Insctructions: Complete the following questions:**

### Imports

In [1]:
import pandas as pd

### Q1. Load the (SuperMarket Analysis.csv) dataset and display the first 5 rows.

In [2]:
df = pd.read_csv("./SuperMarket Analysis.csv")
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

### Q2. Display the dataset shape (rows and columns)

In [3]:
df.shape

(1000, 17)

### Q3. List all column names

In [4]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='str')

### Q4. Identify categorical and numerical columns.

In [5]:
df.dtypes

Invoice ID                     str
Branch                         str
City                           str
Customer type                  str
Gender                         str
Product line                   str
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                      float64
Date                           str
Time                           str
Payment                        str
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [6]:
categories = ['Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Payment']

for category in categories:
    df[category] = df[category].astype('category')

In [7]:
df.dtypes

Invoice ID                      str
Branch                     category
City                       category
Customer type              category
Gender                     category
Product line               category
Unit price                  float64
Quantity                      int64
Tax 5%                      float64
Sales                       float64
Date                            str
Time                            str
Payment                    category
cogs                        float64
gross margin percentage     float64
gross income                float64
Rating                      float64
dtype: object

### Q5. Check for missing values in each column

In [8]:
df.isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

### Q6. Display the data types of each column

In [9]:
df.dtypes

Invoice ID                      str
Branch                     category
City                       category
Customer type              category
Gender                     category
Product line               category
Unit price                  float64
Quantity                      int64
Tax 5%                      float64
Sales                       float64
Date                            str
Time                            str
Payment                    category
cogs                        float64
gross margin percentage     float64
gross income                float64
Rating                      float64
dtype: object

### Q7. Show summary statistics for numerical columns (use pandas method)

In [10]:
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

In [11]:
df[numerical_columns].describe()

,Unit price,Quantity,Tax 5%,Sales,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

### Q8. Filter rows where Sales > 500

In [12]:
df[df['Sales'] > 500].head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7

### Q9. Filter sales in City = "Yangon" and Sales > 200

In [13]:
df[(df['Sales'] > 200) & (df['City'] == 'Yangon')].head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8

### Q10. Sort all orders by Sales in descending order

In [14]:
df.sort_values(by=['Sales'], ascending=False).head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
350,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.65,1042.65,2/15/2019,2:53:00 PM,Credit card,993.0,4.761905,49.65,6.6
167,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.49,1039.29,2/8/2019,4:20:00 PM,Credit card,989.8,4.761905,49.49,8.7
557,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.26,1034.46,1/30/2019,8:23:00 PM,Ewallet,985.2,4.761905,49.26,4.5
699,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.75,1023.75,1/12/2019,4:18:00 PM,Ewallet,975.0,4.761905,48.75,8.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.69,1022.49,3/2/2019,5:16:00 PM,Ewallet,973.8,4.761905,48.69,4.4

### Q11. Sort by Date (ascending) and then Time (ascending)

In [15]:
# df['Date'] = pd.to_datetime(df['Date'], format="%m/%d/%Y")
# df['Time'] = pd.to_datetime(df['Time'], format="%I:%M:%S %p")
df['Date time'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], format="%m/%d/%Y %I:%M:%S %p")
df.sort_values(by=['Date time']).iloc[[0, 1, 2, 997, 998, 999]]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Date time
17,765-26-6951,Alex,Yangon,Member,Female,Sports and travel,72.61,6,21.783,457.443,1/1/2019,10:39:00 AM,Credit card,435.66,4.761905,21.783,6.9,2019-01-01 10:39:00
970,746-04-1077,Cairo,Mandalay,Member,Female,Food and beverages,84.63,10,42.315,888.615,1/1/2019,11:36:00 AM,Credit card,846.30,4.761905,42.315,9.0,2019-01-01 11:36:00
839,271-77-8740,Giza,Naypyitaw,Member,Female,Sports and travel,29.22,6,8.766,184.086,1/1/2019,11:40:00 AM,Ewallet,175.32,4.761905,8.766,5.0,2019-01-01 11:40:00
473,731-59-7531,Cairo,Mandalay,Member,Male,Health and beauty,72.57,8,29.028,609.588,3/30/2019,5:58:00 PM,Cash,580.56,4.761905,29.028,4.6,2019-03-30 17:58:00
643,131-15-8856,Giza,Naypyitaw,Member,Female,Food and beverages,72.52,8,29.008,609.168,3/30/2019,7:26:00 PM,Credit card,580.16,4.761905,29.008,4.0,2019-03-30 19:26:00
963,364-34-2972,Giza,Naypyitaw,Member,Male,Electronic accessories,96.82,3,14.523,304.983,3/30/2019,8:37:00 PM,Cash,290.46,4.761905,14.523,6.7,2019-03-30 20:37:00

### Q12. Sort by Unit price and Quantity

In [16]:
df.sort_values(by=['Unit price', 'Quantity']).head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Date time
944,333-23-2632,Alex,Yangon,Member,Male,Health and beauty,10.08,7,3.5280,74.0880,3/28/2019,8:14:00 PM,Cash,70.56,4.761905,3.5280,4.2,2019-03-28 20:14:00
572,239-48-4278,Alex,Yangon,Member,Male,Food and beverages,10.13,7,3.5455,74.4555,3/10/2019,7:35:00 PM,Ewallet,70.91,4.761905,3.5455,8.3,2019-03-10 19:35:00
784,516-77-6464,Giza,Naypyitaw,Member,Female,Health and beauty,10.16,5,2.5400,53.3400,2/24/2019,1:08:00 PM,Ewallet,50.80,4.761905,2.5400,4.1,2019-02-24 13:08:00
822,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,2:15:00 PM,Cash,10.17,4.761905,0.5085,5.9,2019-02-07 14:15:00
881,115-38-7388,Giza,Naypyitaw,Member,Female,Fashion accessories,10.18,8,4.0720,85.5120,3/30/2019,12:51:00 PM,Credit card,81.44,4.761905,4.0720,9.5,2019-03-30 12:51:00

### Q13. Calculate the total sales in "Sales" per Branch

In [17]:
df.groupby(by=['Branch'])['Sales'].sum()

Branch
Alex     106200.3705
Cairo    106197.6720
Giza     110568.7065
Name: Sales, dtype: float64

### Q14. Calculate average Sales per City

In [18]:
df.groupby(by=['City'])['Sales'].mean()

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Sales, dtype: float64

### Q15. Find the quantities sold per product line

In [19]:
df.groupby(by=['Product line'])['Quantity'].count()

Product line
Electronic accessories    170
Fashion accessories       178
Food and beverages        174
Health and beauty         152
Home and lifestyle        160
Sports and travel         166
Name: Quantity, dtype: int64

### Q16. Calculate average gross income per Gender

In [20]:
df.groupby(by=['Gender'])['gross income'].mean()

Gender
Female    16.234829
Male      14.240749
Name: gross income, dtype: float64

### Q17. Count number of sales per Payment method

In [21]:
df.groupby(by=['Payment'])['Sales'].count()

Payment
Cash           344
Credit card    311
Ewallet        345
Name: Sales, dtype: int64

### Q18. Find maximum Sales per Branch.

In [22]:
df.groupby(by=['Branch'])['Sales'].max()

Branch
Alex     1039.29
Cairo    1022.49
Giza     1042.65
Name: Sales, dtype: float64

### Q19. Find minimum Unit price per Product line.

In [23]:
df.groupby(by=['Product line'])['Unit price'].min()

Product line
Electronic accessories    10.56
Fashion accessories       10.18
Food and beverages        10.13
Health and beauty         10.08
Home and lifestyle        10.53
Sports and travel         10.17
Name: Unit price, dtype: float64

### Q20. Find the sum of gross income per Product line and Branch.

In [24]:
df.groupby(by=['Product line', 'Branch'])['gross income'].sum()

Product line            Branch
Electronic accessories  Alex       872.2435
                        Cairo      811.9735
                        Giza       903.2845
Fashion accessories     Alex       777.7385
                        Cairo      781.5865
                        Giza      1026.6700
Food and beverages      Alex       817.2905
                        Cairo      724.5185
                        Giza      1131.7550
Health and beauty       Alex       599.8930
                        Cairo      951.4600
                        Giza       791.2060
Home and lifestyle      Alex      1067.4855
                        Cairo      835.6745
                        Giza       661.6930
Sports and travel       Alex       922.5095
                        Cairo      951.8190
                        Giza       750.5680
Name: gross income, dtype: float64

### Q21. What is the total quantities sold in Product line: "Electronic accessories"?

In [25]:
(df[df['Product line'] == 'Electronic accessories'])['Quantity'].sum()

np.int64(971)

### Q22. What is the average Sales for female customers?

In [26]:
(df[df['Gender'] == 'Female'])['Sales'].mean()

np.float64(340.9314141856392)

### Q23. What is the most expensive Unit price among Customer type members only?

In [27]:
(df[df['Customer type'] == 'Member'])['Unit price'].max()

np.float64(99.96)

### Q24. How many orders with Rating >= 9 ?

In [28]:
(df[df['Rating'] >= 9])['Invoice ID'].count()

np.int64(166)

### Q25. What is the total Sales for Payment " Credit card " in Branch C?

In [29]:
(df[(df['Payment'] == 'Credit card') & (df['Branch'] == 'Cairo')])['Sales'].sum()

np.float64(37344.8565)